name: ai_detection_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - pillow
  - opencv-python
  - tqdm
  - pip
  - pip:
      - timm
      - huggingface_hub
      - datasets
      - gdown
