name: ai_detection_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - imageio
  - h5py
  - jupyterlab
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Adjust based on your GPU driver
  - ffmpeg
  - dlib
  - cython

  - pip:
    - opencv-python
    - opencv-contrib-python
    - face-alignment
    - mediapipe
    - einops
    - albumentations
    - jsonlines
    - scipy
    - scikit-image
    - imutils
